### ISSUE TITLE
승건씨 안녕하세요?

### ISSUE THREAD

**Issue by JinuCheon** [NoLookCoding/AWP_Backend#10]
그곳에서는 행복하시죠?

@SeungGun

**Comment by SeungGun** [comment]
> 그곳에서는 행복하시죠?
> 
> @SeungGun

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 하하..

**Comment by Yoon-Hae-Min** [comment]
안녕하세요? 지나가다 들렀습니다?

**Comment by JinuCheon** [comment]
네~ 해민씨도 반갑습니다 ^^.

**Comment by Martin0o0** [comment]
지나가다가 저도 들렀습니당! 잘 지내시죠!?

**Comment by JinuCheon** [comment]
네~ 반갑습니다.
모두 이렇게 한 자리에 모여주시니 좋네요.

오늘은 그리운 옛 동료 머쓱씨의 혼을 기리는 시간입니다.

부조금은 이곳으로 보내주시면 됩니다.
국민은행 01026695282 천진우

**Comment by SeungGun** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

아니 다들 누추한 곳에 어떻게... 오셨는지들..
